site_name: Documentation Floris
site_description: Documentation personnelle sur divers sujets informatiques et autres centres d'intérêt.
site_author: Floris Robart
repo_url: https://github.com/FloRobart/Documentations
repo_name: Florobart/Documentation

docs_dir: docs
site_dir: site

theme:
    name: mkdocs
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - navigation.instant
        - toc.follow
        - content.code.copy
    locale: fr
    user_color_mode_toggle: true
    color_mode:
        default_mode: auto
        disable_switch: false
    highlightjs: true
    hljs_style: github
    hljs_style_dark: github-dark

extra_css:
    - css/custom.css

plugins:
    - search:
        lang: fr
    - awesome-pages

markdown_extensions:
    - toc:
        permalink: true
        toc_depth: 4
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - footnotes
    - tables
    - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Florobart

nav:
    - Accueil: index.md
    - Meta & règles:
        - Tous mes projets: 00_meta/all_project.md
        - Règles de documentation: 00_meta/documentation_rules.md
    - Développement:
        - Gestion de projets:
            - Outils de gestion de projets : 01_development/project_management/project_management_tools.md
        - Database:
            - PostgreSQL : 01_development/database/postgresql.md
            - Migration Laravel : 01_development/database/migrations_and_seeders_by_tanvir.md
        - Back-end:
            - Java : 01_development/backend/java.md
            - TypeScript (Node.js/Express) : 01_development/backend/create_api_typescript.md
            - Laravel : 01_development/backend/laravel.md
            - Symfony : 01_development/backend/symfony.md
            - CodeIgniter: 01_development/backend/codeigniter.md
        - Front-end:
            - Flutter : 01_development/frontend/flutter.md
            - React : 01_development/frontend/react.md
        - Déploiement:
            - Mise en production d'une application dockerisée : 01_development/deployment/production_with_docker.md
            - Creation de packets Debian : 01_development/deployment/debian_package_creation.md
            - Mise sous licence d'un projet open source: 01_development/deployment/open_source_licensing_gnu_gpl.md
        - Autres*:
            - Clean code (Codé proprement) : 01_development/others/clean_code.md
            - Developpement web en micro-services (Recommandé): 01_development/others/web_development_micro_service.md
            - Bonne pratiques de développement by ChatGPT : 01_development/others/coding_best_practices_by_chatgpt.md
            - Developpement web en PHP: 01_development/others/web_development_php.md
    - Applications:
        - Installation d'applications Linux divers: 02_applications/installation_usage.md
        - Installation de Docker : 02_applications/docker_installation.md
        - Git: 02_applications/git.md
        - SSH: 02_applications/ssh.md
        - Visual Studio Code: 02_applications/vscode.md
        - Gnome Shell Connect (GSC): 02_applications/gnome_shell_connect.md
        - Ventoy: 02_applications/ventoy.md
        - Connection d'une imprimante HP: 02_applications/hp_printer_connection.md
        - Configuration de Thunderbird pour l'IUT du Havre: 02_applications/thunderbird_iut_le_havre.md
    - Systèmes:
        - Server:
            - Création d'un serveur web PHP: 03_system/server/php_web_server_creation.md
        - Linux:
            - Création d'un dual boot: 03_system/linux/dual_boot.md
            - Utilisation d'outils windows sous Linux: 03_system/linux/windows_on_linux.md
        - Windows:
            - Contournement des sécurités Windows: 03_system/windows/windows_security.md
        - Android:
            - Flashing d'un appareil Android: 03_system/android/flashing_android_device.md
        - Machines virtuelles:
            - Machines virtuels avec VirtualBox: 03_system/virtual_machine/virtual_machines.md
        - Autres:
            - Resolution de problèmes divers sous Linux: 03_system/others/general_manipulation.md
    - Entrepreneuriat:
        - Creation d'une entreprise pour le developpement: 04_entrepreneuriat/company_creation_for_development.md
    - Electronique:
        - Aucune documentation pour le moment: Aucune documentation pour le moment.
    - Autres:
        - Page don Téléthon: 98_others/creation_page_don_telethon.md
